name: JVM publish CI with Gradle

on:
  push:
    tags:
      - 'jvm-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build, test and publish with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: |
           clean build artifactoryPublish -b build.gradle.kts \
             -PartifactoryUser=$SECRET_ARTIFACTORY_PUBLISHER_USER \
             -PartifactoryPass=$SECRET_ARTIFACTORY_PUBLISHER_PASS
